### ISSUE TITLE
examples not getting compiled by default

### ISSUE THREAD

**Issue by niravnshah** [intel/DML#13] opened 2022-02-01 05:33 UTC
As per the documentation [here](https://intel.github.io/DML/documentation/get_started_docs/code_samples_and_examples.html), the examples should be compiled, however, it is not specified in the CMakeLists.txt.

Please add this line to CMakeLists.txt to get the examples compiled when the DML is compiled.

![image](https://user-images.githubusercontent.com/73517208/151917749-518597ff-fb58-4db3-9b94-6b4e885c3018.png)

**Comment by EgorKupaev** [comment] 2022-02-07 09:38
Hi @niravnshah, thank you for pointing out the issue. It seems that this line was accidentally removed and it will be fixed.

**Comment by EgorKupaev** [comment] 2022-03-30 04:20
The issue is fixed.

**Closed as completed by EgorKupaev** 2022-03-30 04:20 UTC
